# Generated by Django 5.0.4 on 2024-04-09 12:08

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('country_name', models.CharField(max_length=100, unique=True)),
                ('photo', models.ImageField(upload_to='country_flag_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('sport_name', models.CharField(max_length=100)),
                ('sport_type', models.CharField(choices=[('team', 'Командный'), ('individual', 'Индивидуальный')], default='individual', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('venue_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_code', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1)),
                ('photo', models.ImageField(default='default_photo.jpg', upload_to=app.models.participant_photo_path)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('result', models.CharField(max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.participant')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=None)),
                ('start_time', models.TimeField(default=None)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sport')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venue')),
            ],
        ),
    ]
