# Generated by Django 5.0.4 on 2024-04-09 12:13

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='photo',
            field=models.ImageField(upload_to=app.models.country_flag_photo_path),
        ),
    ]
