# Generated by Django 5.0.4 on 2024-04-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sport_sport_type_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='sport_type',
            field=models.CharField(choices=[('team', 'Командный'), ('individual', 'Индивидуальный')], max_length=20),
        ),
    ]
