# Generated by Django 5.0.4 on 2024-04-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_discipline_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
