# Generated by Django 5.0.4 on 2024-04-09 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_participant_participant_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
