# Generated by Django 5.0.4 on 2024-04-09 13:44

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_participant_participant_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=50, primary_key=True, serialize=False),
        ),
    ]
