# Generated by Django 5.0.4 on 2024-04-09 13:46

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_venue_venue_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=50, primary_key=True, serialize=False),
        ),
    ]
