# Generated by Django 5.0.4 on 2024-04-10 11:17

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_result_schedule_alter_discipline_discipline_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=50, primary_key=True, serialize=False),
        ),
    ]
