# Generated by Django 5.0.4 on 2024-04-11 11:11

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_venue_venue_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время старта в формате timestamp'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=50, primary_key=True, serialize=False),
        ),
    ]
